spring:
  config:
    activate:
      on-profile: prod
    import: 'aws-parameterstore:'
 
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: ${database.url}
    username: ${database.user}
    password: ${database.pass}

  redis:
    host: 172.31.1.201
    port: 6379

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        color-codes: true
        type:
          descriptor:
            sql: trace
        default_batch_fetch_size: 100
      open-in-view: false

jwt:
  key: 20231120try241map1315be316good9612161catch20231222
  access-token-expiration-minutes: 5
  refresh-token-expiration-minutes: 360

aws:
  paramstore:
    enabled: true
    prefix: /mapbegood
    name: app
    profile-separator: _
    
logging:
  level:
    org:
      springframework:
        web: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace