spring:
  config:
    activate:
      on-profile: prod
    import: 'aws-parameterstore:'
 
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
#    url: jdbc:oracle:thin:@dbmapbegood_medium?TNS_ADMIN=/home/ubuntu/Wallet_DBMAPBEGOOD
#    url: jdbc:oracle:thin:@dbmapbegood_medium?TNS_ADMIN=c:/opt/Wallet_DBMAPBEGOOD
#    username: admin
#    password: Mapbegood2023
    url: ${database.url}
    username: ${database.user}
    password: ${database.pass}

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        highlight_sql: true
        color-codes: true
        type:
          descriptor:
            sql: trace

aws:
  paramstore:
    enabled: true
    prefix: /mapbegood
    name: app
    profile-separator: _
    
logging:
  level:
    org:
      springframework:
        web: debug
