logging:
  level:
    org:
      springframework:
        web: debug
    #        security: debug
#    org.springframework.web.servlet: debug
#    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
#    url: jdbc:oracle:thin:@dbmapbegood_high?TNS_ADMIN=D:/KOSA/proj/3.final/Wallet_DBMAPBEGOOD
    url: jdbc:oracle:thin:@dbmapbegood_medium?TNS_ADMIN=C:/opt/Wallet_DBMAPBEGOOD
    username: admin
    password: Mapbegood2023
#  h2:
#    console:
#      enabled: true
#      path: /h2           # localhost:8080/h2  URL 접속 경로, default : /h2-console
#    datasource:
#      url: jdbc:h2:mem:test # JDBC URL

  jpa:
#    hibernate:
#      ddl-auto: none # 스키마 자동 생성 create-drop?
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        color-codes: true
        type:
          descriptor:
            sql: trace

