spring:
  config:
    import: 'aws-parameterstore:'
    
    #java.lang.IllegalStateException: Unable to load config data from 'aws-paramstore:'
#    import: 'aws-paramstore:' 
  
#  cloud:
#    aws:
#      credentials:
#        access-key: ${s3.access.key}
#        secret-key: ${s3.secret.key}
      
  aws:
    paramstore:
      enabled: true
      prefix: /mapbegood
      name: prod
      profile-separator: _
      
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: ${database.url}
    username: ${database.user}
    password: ${database.pass}

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        highlight_sql: true
        color-codes: true
        type:
          descriptor:
            sql: trace
  
logging:
  level:
    org:
      springframework:
        web: debug
