spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@dbmapbegood_medium?TNS_ADMIN=C:/opt/Wallet_DBMAPBEGOOD
    username: admin
    password: Mapbegood2023

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        highlight_sql: true
        color-codes: true
        type:
          descriptor:
            sql: trace
  
server:
  port: 8080
  servlet:
    context-path: /mapbegood
  

logging:
  level:
    org:
      springframework:
        web: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace