spring:
  config:
    activate:
      on-profile: prod
    import: 'aws-parameterstore:'
 
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: ${database.url}
    username: ${database.user}
    password: ${database.pass}

  redis:
    host: ${redis.host}
    port: ${redis.port}

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        color-codes: true
        type:
          descriptor:
            sql: trace
        default_batch_fetch_size: 100
      open-in-view: false

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${kakao.client.id}
            redirect-uri: "https://api.mapbegood.site/login/oauth2/code/kakao"
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            client-name: Kakao
            provider: kakao
            scope:
              - account_email
              - profile_nickname
              - profile_image
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  mail:
    host: ${mail.host}
    port: ${mail.port}
    username: ${admin.mail}
    password: ${admin.mail.pass}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connection-timeout: 5000
          timeout: 5000
          write-timeout: 5000
    auth-code-expiration-millis: ${mail.auth.code.exp}

jwt:
  key: ${jwt.secret.key}
  access-token-expiration-minutes: ${jwt.access.token.exp}
  refresh-token-expiration-minutes: ${jwt.refresh.token.exp}

cloud:
  aws:
    credentials:
      access-key: ${s3.access.key}
      secret-key: ${s3.secret.key}
    s3:
      bucket: ${aws.s3.bucket.image}
    region:
      static: ap-northeast-2
    stack:
      auto: false

aws:
  paramstore:
    enabled: true
    prefix: /mapbegood
    name: app
    profile-separator: _
    
logging:
  level:
    org:
      springframework:
        web: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace