spring:
  config:
    activate:
      on-profile: local

  output:
    ansi:
      enabled: ALWAYS

  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@dbmapbegood_medium?TNS_ADMIN=C:/opt/Wallet_DBMAPBEGOOD
    username: admin
    password: Mapbegood2023

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        color-codes: true
        type:
          descriptor:
            sql: trace
        default_batch_fetch_size: 100

#  security:
#    oauth2:
#      client:
#        registration:
#          kakao:
#            client-id: d1c3e8aae1df4eb30d44f96550d55977
##            client-secret: ${kakao.client.secret}
#            client-authentication-method: POST
#            authorization-grant-type: authorization_code
#            redirect-uri: "https://ec2-3-36-48-195.ap-northeast-2.compute.amazonaws.com/login/oauth2/kakao"
#            client-name: Kakao
#            provider: kakao
#            scope:
#              - profile_nickname
#              - profile_image
#              - account_email
#        provider:
#          kakao:
#            authorization-uri: https://kauth.kakao.com/oauth/authorize
#            token-uri: https://kauth.kakao.com/oauth/token
#            user-info-uri: https://kapi.kakao.com/v2/user/me
#            user-name-attribute: id

jwt:
  key: 20231120try241map1315be316good9612161catch20231222
  access-token-expiration-minutes: 1440 #5
  refresh-token-expiration-minutes: 360

logging:
  level:
    org:
      springframework:
        web: debug

mail:
  address:
    admin: mapbegood@mail.com