name: Build spring EC2

on:
  push:
    branches: [ "back" ]
  pull_request:
    branches: [ "back" ]
    
env:
  S3_BUCKET_NAME: mapbegood-war
  APP_NAME: mapbegood

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
 
    - name: Build with Maven
      #run: mvn -B package --file pom.xml
      run: mvn -Dmaven.test.skip=true package

    - name: Make zip file
      run: zip -r ./$APP_NAME.zip .
      shell: bash
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}            
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2
   
    - name: Upload to S3
      run: aws s3 cp --region ap-northeast-2 ./$APP_NAME.zip s3://$S3_BUCKET_NAME/$APP_NAME.zip
      
    - name: Code Deploy
      run: >
        aws deploy create-deployment
        --application-name $S3_BUCKET_NAME
        --deployment-config-name CodeDeployDefault.AllAtOnce
        --deployment-group-name $S3_BUCKET_NAME
        --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=$APP_NAME.zip
